//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public string Para12 { get; set; }
        public string Para34 { get; set; }
        public string Para56 { get; set; }
        public string Para78 { get; set; }
        public string Para910 { get; set; }
        public int GroupId { get; set; }
    }
}
